---
- hosts: webservers
  sudo: yes
  vars:
    http_port: 80
    doc_dir: /ansible/
    doc_root: /var/www/html/ansible/
    max_clients: 5
  
  vars_prompt:
    - name: username
      prompt: What is your name? What is your Quest? What is your favourite colour?  
  
  tasks:
  - name: Ensure Apache is installed
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"

  - name: Start Apache is running
    service: name=httpd enabled=yes state=started

  - name: Create Ansible Apache directory
    file: path={{ doc_root }} state=directory mode=0755
  
  - name: Deploy configuration file
    template: src="templates/httpd.j2" dest="/etc/httpd/conf/httpd.conf"
    notify:
      - Restart Apache
  
  - name: Copy site files
    template: src=templates/index.j2 dest={{ doc_root }}/index.html   

  - name: Set permissions on index.html
    file: path={{ doc_root }}/index.html mode=0755

  handlers:
    - name: Restart Apache
      service: name=httpd state=restarted
  
- hosts: dbservers
  sudo: yes

  tasks:
  - name: Ensure MySQL database is installed
    yum: name=mysql-server state=present 
    when: ansible_os_family == "RedHat"

  - name: Ensure MySQL database is running
    service: name=mysqld state=started

- hosts: webservers:dbservers
  sudo: yes

  tasks:
  - name: Stop IPtables service
    service: name=iptables state=stopped


